### ISSUE TITLE
想請教如何做到雙語的切換（中文/英文）

### ISSUE THREAD

**Issue by ShannonHung** [jerryc127/butterfly.js.org#226]
您好，
我在您的原始碼中，想要了解中英文切換的部分。我也參考了您的commit紀錄，一步步嘗試大概是Jul 1, 2023開始有了中英文的切換，但是不管如何嘗試都無法成功，不確定缺少了哪一個部分...。我找了很久的問題ＱＱ也爬了個大網站，但是還是想不透...要走投無路惹。所以想請教缺少了哪一個部分，或是想請教教學！

# 版本
Butterfly version: 4.10.0
hexo-cli: 4.3.1
node: 19.8.1
hexo: 7.0.0

# 過程
因此參考並進行以下步驟：

1. 建立了 `config-en.yml`, `config-butterfly-en.yml` 做了相對的設置，設置包含：
> config-en.yml 
```yml 
# 添加 en 
url: https://butterfly.js.org/en
root: /en/

# 指定啟動的路徑
source_dir: source-en
public_dir: public-en

# 把中文的 source 進行排除
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:
  - source/
```

> _config.yml 
```yml 
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://butterfly.js.org
root: /

# Directory
source_dir: source
public_dir: public

# 主要排除 en 的 source folder 
include:
exclude:
ignore:
  - source-en/
```

2. 設定主題目錄
> _config.butterfly.yml
```yml 
menu:
  # Archives: /archives/ || fas fa-archive
  找文章||fas fa-list:
    目錄: /categories/ || fas fa-folder-open
    標籤: /tags/ || fas fa-tags
    文章: /archives/ || fas fa-archive
  首頁: / || fas fa-home
  關於我: /about/ || fas fa-heart
  相關連結: /link/ || fas fa-link
  語言||fas fa-language:
    English: /en/ || fas fa-e
    中文: / || fas fa-c
```

> config-butterfly-en.yml
```yml 
# Menu 目錄
menu:
  # Archives: /archives/ || fas fa-archive
  Categroies: /categories/ || fas fa-folder-open
  Find Posts ||fas fa-list:
    By Tags: /tags/ || fas fa-tags
    By Posts: /archives/ || fas fa-archive
  Home Page: / || fas fa-home
  About Me: /about/ || fas fa-heart
  Links: /link/ || fas fa-link
  Language||fas fa-language:
    English: / || fas fa-e
    中文: https://localhost:4000/ || fas fa-c # 需要改成 localhost:4000 進行測試
```

3. 於 `source` 中建立 `self/btf.js` 檔案，中英文切換路徑的js檔，如下：
```javascript
(() => {
    const isIncludeEN = item => {
      const key = '/en/'
      return item.includes(key)
    }
  
    window.loadFullPage = (url) => {
      window.location.href = url
    }
  
    const eventFn = (elements, includeEN) => {
      elements.forEach(item => {
        if (!includeEN || !isIncludeEN(item.href)) {
          item.href = `javascript:loadFullPage('${item.href}');`
        }
      })
    }
  
    const nowIncludeEN = isIncludeEN(window.location.href)
# 這裡的網址有修改
    const selector = nowIncludeEN
      ? document.querySelectorAll('a[href^="https://localhost:4000"]')
      : document.querySelectorAll('a[href^="/en/"]')
  
    eventFn(selector, nowIncludeEN)
  })()
```
> config-butterfly-en.yml 與 _config.butterfly.yml
```yml 
inject:
  bottom:
    - <script data-pjax src="/self/btf.js"></script>
```

4. 複製整個 source 資料夾，並且更名為 `source-en`，結構如下：
```bash 
.
├── node_modules
├── scaffolds
├── source
├── source-en # <== here 
├── themes
├── _config.butterfly.yml
├── _config.yml
├── config-butterfly-en.yml 
├── config-en.yml
├── db.json
├── package-lock.json
├── package.json
└── yarn.lock
```

5. `package.json` 參考了裡面的script的部分，透過`npm run en` 根據 `config-en.yml` 產生 `public-en` 資料夾，但是啟動以 _config.yml 啟動
```json 
{ ...
  "scripts": {
    "push": "hexo clean && hexo g && hexo douban && gulp && hexo deploy",
    "show": "hexo clean && hexo g && hexo s",
    "update": "git init && git add . && git commit -m 'backup' && git push origin main",
    "kk": "hexo clean && hexo g && hexo deploy",
    "en": "hexo clean && hexo g && hexo g --config config-en.yml -f && hexo s"
  },
...}
```
# 問題
1. 當我執行 `hexo clean && hexo g && hexo g --config config-en.yml -f && hexo s --config config-en.yml` 的時候以`config-en.yml` 啟動，會無法正確仔入 js 與其他 source 檔案，我認為可能是沒引用到 `config-butterfly-en.yml` ... 但是又不知道該怎麼引用。
![Image](https://i.imgur.com/Joa95kb.png)

3. 因為使用 GitHub Pages，所以部屬於 Github 時，我認為應該主要會以一個config開始進行部署，**想請問是如何同時啟用兩種 config.yml於github page中** ？
    - 找了很久的做法，後來參考到一個比較可能的[網站](https://www.igerm.ee/experience/%E5%AE%8C%E7%BE%8E%E7%9A%84Hexo%E5%A4%9A%E8%AF%AD%E8%A8%80%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88/)，比較可能的作法是另開一個git repository，但是我發現在 `config-en.yml` 看到另一個 git repository，`config-en.yml` 與` _config.yml `是相同的設定，所以可能排除掉這個可能。

> config-en.yml 
```yml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:jerryc127/butterfly-demo.git
  branch: master
  # other deployer
```

> _config.yml
```yml 
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:jerryc127/butterfly-demo.git
  branch: master
  # other deployer
```
